services:
    app:
        build: .
        image: app_users:1.0.0
        ports:
            - "8080:8080"
        container_name: app_users
        command: node --env-file /.env.prd dist/server.js
        volumes:
            - ./.env.prd:/.env.prd
